### ISSUE TITLE
Entorno de desarrollo

### ISSUE THREAD

**Issue by MiguelRubioPavia** [MartiHui/PersonalTools#1]
Tengo instalado visual studio community 2019 con los siguientes módulos:

- Desarrollo de ASP.NET y web
- Desarrollo de escritorio de .NET
- Almacenamiento y procesamiento de datos

Me falta algo mas o con eso puedo ejecutar el proyecto?

**Comment by MiguelRubioPavia** [comment]
Supongo que de un paquete de NuGet?, si lo tienes a mano pásame el nombre sino pues instalo cualquiera que me ofrezca características de SQLite

**Comment by MartiHui** [comment]
https://www.sqlite.org/2021/sqlite-dll-win32-x86-3350500.zip
https://www.sqlite.org/2021/sqlite-tools-win32-x86-3350500.zip

Te descargas esos dos, y los descomprimes en una nueva carpeta en C:/
Una vez hecho, añades la ruta de la nueva carpeta a las variables PATH. Para ello, si usas el buscados de windows "Variables de entorno" te saldrá una opción, la selecciona y te abrirá un pop-up llamado "Propiedades del sistema". Abajo verás un botón de "Variables de entorno". Le das y te mostrará un listado con las variables de entorno. Seleccionas Path para editar y te mostrará otro listado con varias rutas, añades ahí la ruta donde has descomprimido SQLite

**Comment by MiguelRubioPavia** [comment]
Okey pues ahora lo haré, pero pensaba que sería algo relacionado con el gestor de paquetes del propio visual studio.

**Comment by MartiHui** [comment]
También hay paquetes nugget necesarios en el proyecto, pero de eso ya me he encargado yo. Se te deberían descargar con el proyecto.

**Comment by MiguelRubioPavia** [comment]
Si he visto que tengo algunas dependencias instaladas
